[tool.poetry]
name = "anonchatbot"
version = "0.1.0"
description = ""
authors = ["paracosm17"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
